# version: "3.8"

# services:
#   localstack:
#     container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
#     image: localstack/localstack:3.2
#     ports:
#       - "127.0.0.1:4566:4566"            # LocalStack Gateway
#       - "127.0.0.1:4510-4559:4510-4559"  # external services port range
#       - "4500:8080"
#     environment:
#       # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
#       - DEBUG=1
#     volumes:
#       - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
#       - "/var/run/docker.sock:/var/run/docker.sock"

version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:3.2
    network_mode: bridge
    ports:
      - "4566-4599:4566-4599"  
    environment:
      - SERVICES=s3,sns,sqs,dynamodb,apigateway,cloudwatch,lambda,events,logs,iam
      - DEBUG=1 
      - DATA_DIR=/tmp/localstack/data 
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"